// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mytest.proto

package mytest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mytest service

func NewMytestEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mytest service

type MytestService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Mytest_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Mytest_PingPongService, error)
}

type mytestService struct {
	c    client.Client
	name string
}

func NewMytestService(name string, c client.Client) MytestService {
	return &mytestService{
		c:    c,
		name: name,
	}
}

func (c *mytestService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Mytest.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mytestService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Mytest_StreamService, error) {
	req := c.c.NewRequest(c.name, "Mytest.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mytestServiceStream{stream}, nil
}

type Mytest_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type mytestServiceStream struct {
	stream client.Stream
}

func (x *mytestServiceStream) Close() error {
	return x.stream.Close()
}

func (x *mytestServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mytestServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mytestServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mytestServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mytestService) PingPong(ctx context.Context, opts ...client.CallOption) (Mytest_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Mytest.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mytestServicePingPong{stream}, nil
}

type Mytest_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type mytestServicePingPong struct {
	stream client.Stream
}

func (x *mytestServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *mytestServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *mytestServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mytestServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mytestServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *mytestServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mytest service

type MytestHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Mytest_StreamStream) error
	PingPong(context.Context, Mytest_PingPongStream) error
}

func RegisterMytestHandler(s server.Server, hdlr MytestHandler, opts ...server.HandlerOption) error {
	type mytest interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Mytest struct {
		mytest
	}
	h := &mytestHandler{hdlr}
	return s.Handle(s.NewHandler(&Mytest{h}, opts...))
}

type mytestHandler struct {
	MytestHandler
}

func (h *mytestHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MytestHandler.Call(ctx, in, out)
}

func (h *mytestHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MytestHandler.Stream(ctx, m, &mytestStreamStream{stream})
}

type Mytest_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type mytestStreamStream struct {
	stream server.Stream
}

func (x *mytestStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mytestStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mytestStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mytestStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mytestStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *mytestHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MytestHandler.PingPong(ctx, &mytestPingPongStream{stream})
}

type Mytest_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type mytestPingPongStream struct {
	stream server.Stream
}

func (x *mytestPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *mytestPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mytestPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mytestPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mytestPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *mytestPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
