// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/tradier.proto

package tests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Tests service

func NewTestsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Tests service

type TestsService interface {
	Quote(ctx context.Context, in *QuoteRequest, opts ...client.CallOption) (*QuoteResponse, error)
	GetMarketState(ctx context.Context, in *MarketeStateRequest, opts ...client.CallOption) (*MarketeStateResponse, error)
}

type testsService struct {
	c    client.Client
	name string
}

func NewTestsService(name string, c client.Client) TestsService {
	return &testsService{
		c:    c,
		name: name,
	}
}

func (c *testsService) Quote(ctx context.Context, in *QuoteRequest, opts ...client.CallOption) (*QuoteResponse, error) {
	req := c.c.NewRequest(c.name, "Tests.Quote", in)
	out := new(QuoteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testsService) GetMarketState(ctx context.Context, in *MarketeStateRequest, opts ...client.CallOption) (*MarketeStateResponse, error) {
	req := c.c.NewRequest(c.name, "Tests.GetMarketState", in)
	out := new(MarketeStateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tests service

type TestsHandler interface {
	Quote(context.Context, *QuoteRequest, *QuoteResponse) error
	GetMarketState(context.Context, *MarketeStateRequest, *MarketeStateResponse) error
}

func RegisterTestsHandler(s server.Server, hdlr TestsHandler, opts ...server.HandlerOption) error {
	type tests interface {
		Quote(ctx context.Context, in *QuoteRequest, out *QuoteResponse) error
		GetMarketState(ctx context.Context, in *MarketeStateRequest, out *MarketeStateResponse) error
	}
	type Tests struct {
		tests
	}
	h := &testsHandler{hdlr}
	return s.Handle(s.NewHandler(&Tests{h}, opts...))
}

type testsHandler struct {
	TestsHandler
}

func (h *testsHandler) Quote(ctx context.Context, in *QuoteRequest, out *QuoteResponse) error {
	return h.TestsHandler.Quote(ctx, in, out)
}

func (h *testsHandler) GetMarketState(ctx context.Context, in *MarketeStateRequest, out *MarketeStateResponse) error {
	return h.TestsHandler.GetMarketState(ctx, in, out)
}
