// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/tradier_core.proto

package tradier_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TradierCore service

func NewTradierCoreEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TradierCore service

type TradierCoreService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type tradierCoreService struct {
	c    client.Client
	name string
}

func NewTradierCoreService(name string, c client.Client) TradierCoreService {
	return &tradierCoreService{
		c:    c,
		name: name,
	}
}

func (c *tradierCoreService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TradierCore.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TradierCore service

type TradierCoreHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterTradierCoreHandler(s server.Server, hdlr TradierCoreHandler, opts ...server.HandlerOption) error {
	type tradierCore interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type TradierCore struct {
		tradierCore
	}
	h := &tradierCoreHandler{hdlr}
	return s.Handle(s.NewHandler(&TradierCore{h}, opts...))
}

type tradierCoreHandler struct {
	TradierCoreHandler
}

func (h *tradierCoreHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TradierCoreHandler.Call(ctx, in, out)
}
