// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/tcore.proto

package tcore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Tcore service

func NewTcoreEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Tcore service

type TcoreService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tcore_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Tcore_PingPongService, error)
}

type tcoreService struct {
	c    client.Client
	name string
}

func NewTcoreService(name string, c client.Client) TcoreService {
	return &tcoreService{
		c:    c,
		name: name,
	}
}

func (c *tcoreService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tcore.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcoreService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tcore_StreamService, error) {
	req := c.c.NewRequest(c.name, "Tcore.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &tcoreServiceStream{stream}, nil
}

type Tcore_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type tcoreServiceStream struct {
	stream client.Stream
}

func (x *tcoreServiceStream) Close() error {
	return x.stream.Close()
}

func (x *tcoreServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tcoreServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tcoreServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tcoreServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tcoreService) PingPong(ctx context.Context, opts ...client.CallOption) (Tcore_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Tcore.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &tcoreServicePingPong{stream}, nil
}

type Tcore_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type tcoreServicePingPong struct {
	stream client.Stream
}

func (x *tcoreServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *tcoreServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *tcoreServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tcoreServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tcoreServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *tcoreServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Tcore service

type TcoreHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Tcore_StreamStream) error
	PingPong(context.Context, Tcore_PingPongStream) error
}

func RegisterTcoreHandler(s server.Server, hdlr TcoreHandler, opts ...server.HandlerOption) error {
	type tcore interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Tcore struct {
		tcore
	}
	h := &tcoreHandler{hdlr}
	return s.Handle(s.NewHandler(&Tcore{h}, opts...))
}

type tcoreHandler struct {
	TcoreHandler
}

func (h *tcoreHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TcoreHandler.Call(ctx, in, out)
}

func (h *tcoreHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TcoreHandler.Stream(ctx, m, &tcoreStreamStream{stream})
}

type Tcore_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type tcoreStreamStream struct {
	stream server.Stream
}

func (x *tcoreStreamStream) Close() error {
	return x.stream.Close()
}

func (x *tcoreStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tcoreStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tcoreStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tcoreStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *tcoreHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TcoreHandler.PingPong(ctx, &tcorePingPongStream{stream})
}

type Tcore_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type tcorePingPongStream struct {
	stream server.Stream
}

func (x *tcorePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *tcorePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tcorePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tcorePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tcorePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *tcorePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
